export const DEFAULT_WORKSPACE_DIRNAME: "OH-WorkSpace";
export const DEFAULT_HEARTBEAT_INTERVAL_MINUTES: 31;
export const DEFAULT_SOCIAL_GLOBAL_THRESHOLD: 80;
export const DEFAULT_SOCIAL_PER_PEER_THRESHOLD: 200;
export const SOCIAL_THRESHOLD_MIN: 10;
export const SOCIAL_THRESHOLD_MAX: 5000;
